"use client";
import { useState } from "react";

function Section({title, children}){
  return <div className="card p-5"><div className="font-semibold">{title}</div><div className="mt-3 space-y-3">{children}</div></div>;
}
function Field({ label, required, children }){
  return (<label className="block"><div className="label">{label} {required && <span className="text-red-500">*</span>}</div>{children}</label>);
}
function Input(props){ return <input {...props} className="input" /> }
function Textarea(props){ return <textarea {...props} className="input" /> }

export default function Page(){
  const [form, setForm] = useState({
    firstName:"", lastName:"", shareName:true, email:"", school:"", major:"",
    remainingBalance:"", totalBalance:"", paymentsRemaining:"",
    employer:"", jobTitle:"", annualSalary:"", story:"", aspirations:"",
    verification:null, consent:false
  });
  const [submitted, setSubmitted] = useState(null);
  const update = (k,v)=> setForm(prev=>({...prev,[k]:v}));

  async function handleSubmit(e){
    e.preventDefault();
    if(!form.verification || !form.consent){ alert("Please upload your statement and provide consent."); return; }
    const fd = new FormData();
    Object.entries(form).forEach(([k,v])=>{
      if(k==="verification"){ if(v) fd.append("verification", v); }
      else fd.append(k, String(v));
    });
    const res = await fetch("/api/students", { method: "POST", body: fd });
    const data = await res.json();
    setSubmitted(data.student);
  }

  return (
    <div className="container-narrow py-8">
      <h2 className="text-2xl font-semibold tracking-tight">Apply as a student</h2>
      <p className="mt-1 text-gray-600">Upload verification (PDF/DOC), share your story, and choose whether to display your real name or an autogenerated alias.</p>

      {!submitted ? (
        <form className="mt-6 space-y-4 max-w-3xl" onSubmit={handleSubmit}>
          <Section title="Identity">
            <div className="grid gap-4 md:grid-cols-2">
              <Field label="First name"><Input value={form.firstName} onChange={e=>update("firstName", e.target.value)} placeholder="Jane" /></Field>
              <Field label="Last name"><Input value={form.lastName} onChange={e=>update("lastName", e.target.value)} placeholder="Doe" /></Field>
              <Field label="Email" required><Input type="email" required value={form.email} onChange={e=>update("email", e.target.value)} placeholder="you@example.com" /></Field>
              <label className="inline-flex items-center gap-2 mt-6">
                <input type="checkbox" checked={form.shareName} onChange={e=>update("shareName", e.target.checked)} />
                <span className="text-sm text-gray-700">Display my real name (otherwise an alias is used)</span>
              </label>
            </div>
          </Section>

          <Section title="Education">
            <div className="grid gap-4 md:grid-cols-2">
              <Field label="School" required><Input required value={form.school} onChange={e=>update("school", e.target.value)} placeholder="e.g. USC" /></Field>
              <Field label="Major"><Input value={form.major} onChange={e=>update("major", e.target.value)} placeholder="Computer Science" /></Field>
            </div>
          </Section>

          <Section title="Loan details">
            <div className="grid gap-4 md:grid-cols-3">
              <Field label="Remaining balance ($)"><Input type="number" value={form.remainingBalance} onChange={e=>update("remainingBalance", e.target.value)} placeholder="0" /></Field>
              <Field label="Total balance ($)"><Input type="number" value={form.totalBalance} onChange={e=>update("totalBalance", e.target.value)} placeholder="0" /></Field>
              <Field label="Payments remaining"><Input type="number" value={form.paymentsRemaining} onChange={e=>update("paymentsRemaining", e.target.value)} placeholder="72" /></Field>
            </div>
          </Section>

          <Section title="Story & aspirations">
            <Field label="Your story"><Textarea rows={3} value={form.story} onChange={e=>update("story", e.target.value)} placeholder="Share your background and what support would mean" /></Field>
            <Field label="Aspirations"><Textarea rows={2} value={form.aspirations} onChange={e=>update("aspirations", e.target.value)} placeholder="What are you working toward?" /></Field>
          </Section>

          <Section title="Verification & consent">
            <Field label="Verification (PDF or DOC)" required>
              <input type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                     onChange={(e)=>update("verification", e.target.files?.[0]||null)}
                     className="w-full rounded-xl border bg-white px-3 py-2" />
              {form.verification && <div className="mt-2 text-sm text-gray-600">Selected: <span className="font-medium">{form.verification.name}</span></div>}
            </Field>
            <label className="inline-flex items-center gap-2">
              <input type="checkbox" checked={form.consent} onChange={e=>update("consent", e.target.checked)} />
              <span className="text-sm text-gray-700">I consent to share my information for fundraising and verification.</span>
            </label>
          </Section>

          <div className="flex gap-3">
            <button type="submit" className="btn btn-primary">Submit application</button>
            <button type="button" onClick={()=>setForm({firstName:"", lastName:"", shareName:true, email:"", school:"", major:"", remainingBalance:"", totalBalance:"", paymentsRemaining:"", employer:"", jobTitle:"", annualSalary:"", story:"", aspirations:"", verification:null, consent:false})} className="btn btn-ghost">Reset</button>
          </div>
        </form>
      ) : (
        <div className="mt-6 max-w-2xl card p-5">
          <div className="font-semibold">Application received</div>
          <div className="mt-2 text-sm text-gray-700">Thanks, {submitted.firstName || "Student"}! We’ll verify your information shortly. Share your profile link with supporters once live.</div>
          <div className="mt-3 text-sm"><span className="text-gray-500">File:</span> <span className="font-medium">{submitted.verificationFileName}</span></div>
          <div className="mt-3"><a className="text-indigo-700 hover:underline" href={`/s/${submitted.id}`}>Preview your profile</a> (link will work after verification).</div>
        </div>
      )}
    </div>
  );
}